name: Unit Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.22

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run linting and type checking
        run: |
          bun run check
          bun run check-types

      - name: Run unit tests - Web
        run: bun run test
        working-directory: apps/web

      - name: Run unit tests - Backend
        run: bun run test
        working-directory: packages/backend

      - name: Generate test coverage - Web
        run: bun run test:coverage
        working-directory: apps/web

      - name: Generate test coverage - Backend
        run: bun run test:coverage
        working-directory: packages/backend